<?php
namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantacionesRepository extends EntityRepository
{
  public function findArea($id)
  {
      $em = $this->getEntityManager();
      $dql = "SELECT ST_AREA(p.geom)/10000 as area
              FROM AppBundle:Plantaciones p
              where p.id = :id";
      $query = $em->createQuery($dql);
      $query->setParameter('id', $id);
      $plantaciones = $query->getSingleResult();
      return $plantaciones;
  }

    public function findPlantacionWithArea($id)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT p as plantacion, ST_AREA(p.geom)/10000 as area, ST_AsGeoJson(ST_TRANSFORM(p.geom,4326)) as geom
                FROM AppBundle:Plantaciones p
                where p.id = :id";
        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);
        $plantaciones = $query->getSingleResult();
        return $plantaciones;
    }
}
