# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     plantaciones_manager:
        class: AppBundle\Controller\PlantacionesController
        arguments: [ "@doctrine.orm.entity_manager" ]

     app.form.type.actividades_plantaciones:
        class: AppBundle\Form\ActividadesPlantacionesType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type }

     app.form.type.actividades_titulares:
        class: AppBundle\Form\ActividadesTitularesType
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type }

     app.form.type.plantaciones:
       class: AppBundle\Form\PlantacionesType
       arguments: [ "@doctrine.orm.entity_manager" ]
       tags:
         -  { name: form.type }

     app.ldap:
        class: Symfony\Component\Ldap\LdapClient
        arguments: [%ldap_server%]
